export const EVENT = {
  ADD_TASK: "ADDTASK",
  UPDATE_TASK: "UPDATETASK",
  DELETE_TASK: "DELETETASK",
  APPLY_FILTERS: "APPLYFILTERS",
  REVIVE_FILTERS: "REVIVEFILTERS",
  REVERT_ADD_TASK: "REVERTADDTASK",
  REVERT_UPDATE_TASK: "REVERTUPDATETASK",
  REVERT_DELETE_TASK: "REVERTDELETETASK",
  UPDATE_TASK_LIST: "UPDATETASKLIST",
  UPDATE_FILTERS: "UPDATEFILTERS",
  FAILURE: "FAILURE",
};
